/**
 * Estados y municipios de Venezuela para los filtros del directorio.
 * Fuente: dataset oficial (ISO 3166-2:VE). Las parroquias se omiten: el
 * directorio sólo filtra por estado y municipio.
 */
export interface EstadoVE {
  estado: string
  municipios: string[]
}

export const VENEZUELA: EstadoVE[] = [
  {
    estado: 'Distrito Capital',
    municipios: ['Libertador'],
  },
  {
    estado: 'Amazonas',
    municipios: ['Alto Orinoco', 'Atabapo', 'Atures', 'Autana', 'Manapiare', 'Maroa', 'Río Negro'],
  },
  {
    estado: 'Anzoátegui',
    municipios: [
      'Anaco',
      'Aragua',
      'Bolívar',
      'Bruzual',
      'Cajigal',
      'Carvajal',
      'Diego Bautista Urbaneja',
      'Freites',
      'Guanipa',
      'Guanta',
      'Independencia',
      'Libertad',
      'McGregor',
      'Miranda',
      'Monagas',
      'Peñalver',
      'Píritu',
      'San Juan de Capistrano',
      'Santa Ana',
      'Simón Rodríguez',
      'Sotillo',
    ],
  },
  {
    estado: 'Apure',
    municipios: [
      'Achaguas',
      'Biruaca',
      'Muñoz',
      'Páez',
      'Pedro Camejo',
      'Rómulo Gallegos',
      'San Fernando',
    ],
  },
  {
    estado: 'Aragua',
    municipios: [
      'Bolívar',
      'Camatagua',
      'Francisco Linares Alcántara',
      'Girardot',
      'José Ángel Lamas',
      'José Félix Ribas',
      'José Rafael Revenga',
      'Libertador',
      'Mario Briceño Iragorry',
      'Ocumare de la Costa de Oro',
      'San Casimiro',
      'San Sebastián',
      'Santiago Mariño',
      'Santos Michelena',
      'Sucre',
      'Tovar',
      'Urdaneta',
      'Zamora',
    ],
  },
  {
    estado: 'Barinas',
    municipios: [
      'Alberto Arvelo Torrealba',
      'Andrés Eloy Blanco',
      'Antonio José de Sucre',
      'Arismendi',
      'Barinas',
      'Bolívar',
      'Cruz Paredes',
      'Ezequiel Zamora',
      'Obispos',
      'Pedraza',
      'Rojas',
      'Sosa',
    ],
  },
  {
    estado: 'Bolívar',
    municipios: [
      'Angostura',
      'Caroní',
      'Cedeño',
      'El Callao',
      'Gran Sabana',
      'Heres',
      'Piar',
      'Roscio',
      'Sifontes',
      'Sucre',
      'Padre Pedro Chien',
    ],
  },
  {
    estado: 'Carabobo',
    municipios: [
      'Bejuma',
      'Carlos Arvelo',
      'Diego Ibarra',
      'Guacara',
      'Mora',
      'Libertador',
      'Los Guayos',
      'Miranda',
      'Montalbán',
      'Naguanagua',
      'Puerto Cabello',
      'San Diego',
      'San Joaquín',
      'Valencia',
    ],
  },
  {
    estado: 'Cojedes',
    municipios: [
      'Anzoátegui',
      'Tinaquillo',
      'Girardot',
      'Lima Blanco',
      'Pao de San Juan Bautista',
      'Ricaurte',
      'Rómulo Gallegos',
      'San Carlos',
      'Tinaco',
    ],
  },
  {
    estado: 'Delta Amacuro',
    municipios: ['Antonio Díaz', 'Casacoima', 'Pedernales', 'Tucupita'],
  },
  {
    estado: 'Falcón',
    municipios: [
      'Acosta',
      'Bolívar',
      'Buchivacoa',
      'Carirubana',
      'Colina',
      'Dabajuro',
      'Democracia',
      'Falcón',
      'Federación',
      'Jacura',
      'Los Taques',
      'Manaure',
      'Mauroa',
      'Miranda',
      'Monseñor Iturriza',
      'Palmasola',
      'Petit',
      'Píritu',
      'San Francisco',
      'Sucre',
      'Silva',
      'Tocópero',
      'Unión',
      'Urumaco',
      'Zamora',
    ],
  },
  {
    estado: 'Guárico',
    municipios: [
      'Camaguán',
      'Chaguaramas',
      'El Socorro',
      'Infante',
      'Las Mercedes',
      'Mellado',
      'Miranda',
      'Monagas',
      'Ortiz',
      'Ribas',
      'Roscio',
      'San Gerónimo de Guayabal',
      'San José de Guaribe',
      'Santa María de Ipire',
      'Zaraza',
    ],
  },
  {
    estado: 'Lara',
    municipios: [
      'Andrés Eloy Blanco',
      'Crespo',
      'Iribarren',
      'Jiménez',
      'Morán',
      'Palavecino',
      'Simón Planas',
      'Torres',
      'Urdaneta',
    ],
  },
  {
    estado: 'Mérida',
    municipios: [
      'Alberto Adriani',
      'Andrés Bello',
      'Antonio Pinto Salinas',
      'Aricagua',
      'Arzobispo Chacón',
      'Campo Elías',
      'Caracciolo Parra Olmedo',
      'Cardenal Quintero',
      'Guaraque',
      'Julio César Salas',
      'Justo Briceño',
      'Libertador',
      'Miranda',
      'Obispo Ramos de Lora',
      'Padre Noguera',
      'Pueblo Llano',
      'Rangel',
      'Rivas Dávila',
      'Santos Marquina',
      'Sucre',
      'Tovar',
      'Tulio Febres Cordero',
      'Zea',
    ],
  },
  {
    estado: 'Miranda',
    municipios: [
      'Acevedo',
      'Andrés Bello',
      'Baruta',
      'Brión',
      'Buroz',
      'Carrizal',
      'Chacao',
      'Cristóbal Rojas',
      'El Hatillo',
      'Guaicaipuro',
      'Independencia',
      'Lander',
      'Los Salias',
      'Páez',
      'Paz Castillo',
      'Pedro Gual',
      'Plaza',
      'Simón Bolívar',
      'Sucre',
      'Urdaneta',
      'Zamora',
    ],
  },
  {
    estado: 'Monagas',
    municipios: [
      'Acosta',
      'Aguasay',
      'Bolívar',
      'Caripe',
      'Cedeño',
      'Ezequiel Zamora',
      'Libertador',
      'Maturín',
      'Piar',
      'Punceres',
      'Santa Bárbara',
      'Sotillo',
      'Uracoa',
    ],
  },
  {
    estado: 'Nueva Esparta',
    municipios: [
      'Antolín del Campo',
      'Arismendi',
      'Díaz',
      'García',
      'Gómez',
      'Maneiro',
      'Marcano',
      'Mariño',
      'Península de Macanao',
      'Tubores',
      'Villalba',
    ],
  },
  {
    estado: 'Portuguesa',
    municipios: [
      'Agua Blanca',
      'Araure',
      'Esteller',
      'Guanare',
      'Guanarito',
      'Monseñor José Vicente de Unda',
      'Ospino',
      'Páez',
      'Papelón',
      'San Genaro de Boconoíto',
      'San Rafael de Onoto',
      'Santa Rosalía',
      'Sucre',
      'Turén',
    ],
  },
  {
    estado: 'Sucre',
    municipios: [
      'Andrés Eloy Blanco',
      'Andrés Mata',
      'Arismendi',
      'Benítez',
      'Bermúdez',
      'Bolívar',
      'Cajigal',
      'Cruz Salmerón Acosta',
      'Libertador',
      'Mariño',
      'Mejía',
      'Montes',
      'Ribero',
      'Sucre',
      'Valdez',
    ],
  },
  {
    estado: 'Táchira',
    municipios: [
      'Andrés Bello',
      'Antonio Rómulo Costa',
      'Ayacucho',
      'Bolívar',
      'Cárdenas',
      'Córdoba',
      'Fernández Feo',
      'Francisco de Miranda',
      'García de Hevia',
      'Guásimos',
      'Independencia',
      'Jáuregui',
      'José María Vargas',
      'Junín',
      'Libertad',
      'Libertador',
      'Lobatera',
      'Michelena',
      'Panamericano',
      'Pedro María Ureña',
      'Rafael Urdaneta',
      'Samuel Darío Maldonado',
      'San Cristóbal',
      'Seboruco',
      'Simón Rodríguez',
      'Sucre',
      'Torbes',
      'Uribante',
      'San Judas Tadeo',
    ],
  },
  {
    estado: 'Trujillo',
    municipios: [
      'Andrés Bello',
      'Boconó',
      'Bolívar',
      'Candelaria',
      'Carache',
      'Escuque',
      'José Felipe Márquez Cañizalez',
      'Juan Vicente Campos Elías',
      'La Ceiba',
      'Miranda',
      'Monte Carmelo',
      'Motatán',
      'Pampán',
      'Pampanito',
      'Rafael Rangel',
      'San Rafael de Carvajal',
      'Sucre',
      'Trujillo',
      'Urdaneta',
      'Valera',
    ],
  },
  {
    estado: 'Vargas',
    municipios: ['Vargas'],
  },
  {
    estado: 'Yaracuy',
    municipios: [
      'Arístides Bastidas',
      'Bolívar',
      'Bruzual',
      'Cocorote',
      'Independencia',
      'José Antonio Páez',
      'La Trinidad',
      'Manuel Monge',
      'Nirgua',
      'Peña',
      'San Felipe',
      'Sucre',
      'Urachiche',
      'Veroes',
    ],
  },
  {
    estado: 'Zulia',
    municipios: [
      'Almirante Padilla',
      'Baralt',
      'Cabimas',
      'Catatumbo',
      'Colón',
      'Francisco Javier Pulgar',
      'Páez',
      'Jesús Enrique Lossada',
      'Jesús María Semprún',
      'La Cañada de Urdaneta',
      'Lagunillas',
      'Machiques de Perijá',
      'Mara',
      'Maracaibo',
      'Miranda',
      'Rosario de Perijá',
      'San Francisco',
      'Santa Rita',
      'Simón Bolívar',
      'Sucre',
      'Valmore Rodríguez',
    ],
  },
]

export const ESTADOS_VENEZUELA: string[] = VENEZUELA.map((e) => e.estado)

/** Municipios de un estado (vacío si el estado no existe o no se eligió). */
export function municipiosDe(estado: string): string[] {
  return VENEZUELA.find((e) => e.estado === estado)?.municipios ?? []
}
